# 项目信息配置
project:
  name: 伊娃
#  mode: demo
  version: 1.0.0
  env: development
#  env: production

# WEB服务器配置
server:
  port: 10011

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/db_eva?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # JSON返回配置
  jackson:
    # 默认时区
    time-zone: GMT+8
    # 默认日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
  # Servlet配置
  servlet:
    multipart:
      # 最大请求参数大小
      max-request-size: 20MB
      # 最大文件参数大小
      max-file-size: 20MB

# MyBatis配置
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 缓存设置
cache:
  session:
    # 会话过期时长(s)
    expire: 1800
  captcha:
    # 验证码过期时长(s)
    expire: 300

# 跟踪日志
trace:
  # 开启智能跟踪模式
  smart: true
  # 排除跟踪的URL正则
  exclude-patterns: .+/list[a-zA-Z0-9\-\_]*$, .+/tree[a-zA-Z0-9\-\_]*$, .+/page[a-zA-Z0-9\-\_]*$, .+/all[a-zA-Z0-9\-\_]*$, /swagger-resources.*

# 对象存储
oss:
  # 文件访问前缀
  access-prefix: /resource

# Swagger配置
swagger:
  host:
  title: ${project.name}接口文档
  description: ${project.name}接口文档
  enabled: true
  # 禁用swagger时的重定向地址
  redirect-uri: /

# 日志配置
logback:
  level: INFO
  appender: ${project.env}
# dao层的日志设置为debug，方便查看sql
logging:
  level:
    com.eva.dao: debug